# Generated by Django 4.2.6 on 2023-11-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
